### ISSUE TITLE
Panic cause closing a closed chanel when ListUsers followed by UserByEmail

### ISSUE THREAD

**Issue by orian** [google/identity-toolkit-go-client#27]
When I change the order (first call UserByEmail then ListUsers), everything works fine.

``` go
package main

import (
	"fmt"
	"github.com/google/identity-toolkit-go-client/gitkit"
	"golang.org/x/net/context"
)

func main() {
	fmt.Println("staring...")
	config := &gitkit.Config{
		WidgetURL:                "http://localhost/gitkit",
		CookieName:               "gtoken",
		GoogleAppCredentialsPath: "/home/orian/tmp/google-identity-toolkit/validation/project-service-account.json",
	}
	client, err := gitkit.New(context.Background(), config)
	if err != nil {
		fmt.Printf("some problem: %s", err)
		return
	}

	fmt.Println("users")
	ul := client.ListUsers(context.Background())
	if ul.Error != nil {
		fmt.Printf("Err: %s", ul.Error)
		return
	}
	for u := range ul.C {
		fmt.Println(u.Email)
	}

	fmt.Println("a specific user")
	u,err := client.UserByEmail(context.Background(), "pawelszczur@gmail.com")
	if err != nil {
		fmt.Printf("err getting user: %s\n", err)
		return
	}else {
		fmt.Printf("got user: %s\n", u.DisplayName)
	}

	fmt.Println("...ending")
}
```

```
panic: close of closed channel

goroutine 5 [running]:
github.com/google/identity-toolkit-go-client/gitkit.(*UserList).start.func1(0xc820011680, 0x7fe077c68668, 0xc82000ad80, 0xc8200222a0)
	/gopath/src/github.com/google/identity-toolkit-go-client/gitkit/gitkit.go:243 +0x217
created by github.com/google/identity-toolkit-go-client/gitkit.(*UserList).start
	/gopath/src/github.com/google/identity-toolkit-go-client/gitkit/gitkit.go:251 +0x8c
```

**Comment by sthomp** [comment]
I've noticed this issue for any client commands after `ListUsers`. Im trying to write a script that iterates over `ListUsers` and then deletes them but this doesnt seem possible at the moment.
